version: '3.4'

services:
  moviedb: 
    container_name: moviedb
    image: mongo
    volumes: 
      - mongo_data:/data/db
    restart: always 

  mr.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://moviedb:27017
    depends_on: 
      - moviedb
    ports:
     - "5000:80"
